services:
    php:
        build: .docker/php
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:delegated
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    db:
        image: percona/percona-server:8.0.36-28.1-multi
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            TZ: ${TZ:-Europe/Moscow}
        volumes:
            - volume_db:/var/lib/mysql:consistent
            - .docker/db:/etc/my.cnf.d:ro
        ports:
            - "127.0.0.1:53306:3306"
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - "6379:6379"
volumes:
    volume_db:
        name: db
        external: false
